### ISSUE TITLE
puppet-alternatives version

### ISSUE THREAD

**Issue by sandwitch** [treydock/puppet-slurm#51]
Is it possible to bump the puppet-alternatives version to 5.1.0? Should i create a pull request?

**Comment by treydock** [comment]
Some unreleased changes now support `<6.0.0`.  Once I finish testing the changes to support 23.02 there will be new release that supports alternatives 5.1.0.

https://github.com/treydock/puppet-slurm/blob/1816a0d938098d7087fa26741d3781d82196e032/metadata.json#L53

**Comment by treydock** [comment]
This is released as 3.0.0
